### ISSUE TITLE
Can't get metadata.

### ISSUE THREAD

**Issue by guillevg** [micromark/micromark-extension-frontmatter#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Steps to reproduce

I am trying to extract metadata from the frontmatter of a markdown file. The following code does work, but I only get the HTML from the markdown. 

```
import {micromark} from 'https://esm.sh/micromark@3?bundle'
import {frontmatter, frontmatterHtml} from 'https://esm.sh/micromark-extension-frontmatter@2?bundle'
import {math, mathHtml} from 'https://esm.sh/micromark-extension-math@3?bundle'

fetch('math_document.md')
  .then(response => response.text())
  .then((data) => {
    const output = micromark(data, {
      extensions: [math(), frontmatter()],
      htmlExtensions: [mathHtml(), frontmatterHtml()]
    });
    console.log(output);
  })
```

### Expected behavior

I would like to get an object with both the HTML and the metadata.

### Actual behavior

I only get HTML. It's as if the only thing this extension does is remove the frontmatter to leave only markdown? Any step in the right direction would be greatly appreciated.

**Comment by wooorm** [comment]
That’s not what this project does. micromark is a markdown parser. It parses markdown. This package is an extension for micromark to allow different fronmatter syntax extensions in markdown.

These things are not YAML parsers. If you want to parse YAML, use a YAML parser. And something that understands YAML frontmatter. Here’s a convenience wrapper to do both: https://github.com/vfile/vfile-matter.

**Comment by guillevg** [comment]
All clear now. Thank you!
